// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RelativeRank.Data;

namespace RelativeRank.Migrations
{
    [DbContext(typeof(RelativeRankContext))]
    [Migration("20191223031207_sf")]
    partial class sf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RelativeRank.EntityFrameworkEntities.Show", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("shows");
                });

            modelBuilder.Entity("RelativeRank.EntityFrameworkEntities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("RelativeRank.EntityFrameworkEntities.UserToShowMapping", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Showname")
                        .HasColumnName("showname")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnName("rank")
                        .HasColumnType("integer");

                    b.HasKey("Username", "Showname");

                    b.HasIndex("Showname");

                    b.HasIndex("Username", "Rank")
                        .IsUnique()
                        .HasName("uq_rank_unique_to_user");

                    b.ToTable("user_to_show_mapping");
                });

            modelBuilder.Entity("RelativeRank.EntityFrameworkEntities.UserToShowMapping", b =>
                {
                    b.HasOne("RelativeRank.EntityFrameworkEntities.Show", "ShownameNavigation")
                        .WithMany("UserToShowMapping")
                        .HasForeignKey("Showname")
                        .HasConstraintName("FK__user_to_s__shown__0D7A0286")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelativeRank.EntityFrameworkEntities.User", "UsernameNavigation")
                        .WithMany("UserToShowMapping")
                        .HasForeignKey("Username")
                        .HasConstraintName("FK__user_to_s__usern__0C85DE4D")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
